---
- name: Check for ransom-alarm service
  hosts: sambas
  tasks:
  - name: Alert if ransom-alarm service not running 
    cron:
      minute="6" 
      name="Alert if ransom-alarm service is not running --Antonio Abella 2/26/17" 
      user="root" 
      job="PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin /root/scripts/maintenance/check-ransom-alarm-running.sh\n\n"
      #state=absent
...
